// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// CreateEdit implements createEdit operation.
	//
	// Create an edit.
	//
	// POST /v1/edit
	CreateEdit(ctx context.Context, req *EditRequest) (CreateEditRes, error)
	// ListEdits implements listEdits operation.
	//
	// List edits.
	//
	// GET /v1/edits
	ListEdits(ctx context.Context) ([]Edit, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
