// Code generated by ogen, DO NOT EDIT.

package api

import (
	"net/http"

	"github.com/ogen-go/ogen/validate"
)

func decodeCreateEditResponse(resp *http.Response) (res CreateEditRes, _ error) {
	switch resp.StatusCode {
	case 202:
		// Code 202.
		return &CreateEditAccepted{}, nil
	case 400:
		// Code 400.
		return &CreateEditBadRequest{}, nil
	}
	return res, validate.UnexpectedStatusCodeWithResponse(resp)
}
