// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// CreateEdit implements createEdit operation.
//
// Create an edit.
//
// POST /v1/edit
func (UnimplementedHandler) CreateEdit(ctx context.Context, req *EditRequest) (r CreateEditRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListEdits implements listEdits operation.
//
// List edits.
//
// GET /v1/edits
func (UnimplementedHandler) ListEdits(ctx context.Context) (r []Edit, _ error) {
	return r, ht.ErrNotImplemented
}
