server {
    listen 8080;
    server_name _;

    root /data;

    location / {
        autoindex on;
    }

    location /tiles/ {
        add_header Cache-Control "public, max-age=31536000, immutable";
        add_header Access-Control-Allow-Origin *;
    }

    location = /tiles.json {
        add_header Content-Type application/json;
        add_header Access-Control-Allow-Origin *;
    }

    # Required for MapLibre
    add_header Access-Control-Allow-Origin *;
}
