// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package data

type Edit struct {
	ID        int64   `json:"id"`
	Name      string  `json:"name"`
	Author    string  `json:"author"`
	Prompt    string  `json:"prompt"`
	StartLng  float64 `json:"start_lng"`
	StartLat  float64 `json:"start_lat"`
	EndLng    float64 `json:"end_lng"`
	EndLat    float64 `json:"end_lat"`
	CreatedAt string  `json:"created_at"`
}
