// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package data

import (
	"context"
)

const createEdit = `-- name: CreateEdit :one
INSERT INTO edits (
    name,
    author,
    prompt,
    start_lng,
    start_lat,
    end_lng,
    end_lat
) VALUES (
    ?, ?, ?, ?, ?, ?, ?
)
RETURNING id, name, author, prompt, start_lng, start_lat, end_lng, end_lat, created_at
`

type CreateEditParams struct {
	Name     string  `json:"name"`
	Author   string  `json:"author"`
	Prompt   string  `json:"prompt"`
	StartLng float64 `json:"start_lng"`
	StartLat float64 `json:"start_lat"`
	EndLng   float64 `json:"end_lng"`
	EndLat   float64 `json:"end_lat"`
}

func (q *Queries) CreateEdit(ctx context.Context, arg CreateEditParams) (Edit, error) {
	row := q.db.QueryRowContext(ctx, createEdit,
		arg.Name,
		arg.Author,
		arg.Prompt,
		arg.StartLng,
		arg.StartLat,
		arg.EndLng,
		arg.EndLat,
	)
	var i Edit
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Author,
		&i.Prompt,
		&i.StartLng,
		&i.StartLat,
		&i.EndLng,
		&i.EndLat,
		&i.CreatedAt,
	)
	return i, err
}

const deleteEdit = `-- name: DeleteEdit :exec
DELETE FROM edits
WHERE id = ?
`

func (q *Queries) DeleteEdit(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteEdit, id)
	return err
}

const getEdit = `-- name: GetEdit :one
SELECT id, name, author, prompt, start_lng, start_lat, end_lng, end_lat, created_at FROM edits
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetEdit(ctx context.Context, id int64) (Edit, error) {
	row := q.db.QueryRowContext(ctx, getEdit, id)
	var i Edit
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Author,
		&i.Prompt,
		&i.StartLng,
		&i.StartLat,
		&i.EndLng,
		&i.EndLat,
		&i.CreatedAt,
	)
	return i, err
}

const listEdits = `-- name: ListEdits :many
SELECT id, name, author, prompt, start_lng, start_lat, end_lng, end_lat, created_at FROM edits
ORDER BY created_at DESC
`

func (q *Queries) ListEdits(ctx context.Context) ([]Edit, error) {
	rows, err := q.db.QueryContext(ctx, listEdits)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Edit
	for rows.Next() {
		var i Edit
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Author,
			&i.Prompt,
			&i.StartLng,
			&i.StartLat,
			&i.EndLng,
			&i.EndLat,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEditsByAuthor = `-- name: ListEditsByAuthor :many
SELECT id, name, author, prompt, start_lng, start_lat, end_lng, end_lat, created_at FROM edits
WHERE author = ?
ORDER BY created_at DESC
`

func (q *Queries) ListEditsByAuthor(ctx context.Context, author string) ([]Edit, error) {
	rows, err := q.db.QueryContext(ctx, listEditsByAuthor, author)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Edit
	for rows.Next() {
		var i Edit
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Author,
			&i.Prompt,
			&i.StartLng,
			&i.StartLat,
			&i.EndLng,
			&i.EndLat,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
