/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/edit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create an edit */
        post: operations["createEdit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        EditRequest: {
            /**
             * @description Human-readable name for this edit
             * @example Relocate bus stop
             */
            name: string;
            /**
             * @description Name or identifier of the person submitting the edit
             * @example jane.doe
             */
            author: string;
            /**
             * @description Free-text description of the desired edit
             * @example Move the bus stop 20 metres north to improve pedestrian access
             */
            prompt: string;
            start: components["schemas"]["GeoJsonPoint"];
            end: components["schemas"]["GeoJsonPoint"];
        };
        GeoJsonPoint: {
            /** @enum {string} */
            type: "Point";
            /**
             * @description [longitude, latitude] in WGS84
             * @example [
             *       25.004,
             *       60.1699
             *     ]
             */
            coordinates: number[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    createEdit: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EditRequest"];
            };
        };
        responses: {
            /** @description Edit accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid request body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
